name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and setup SonarScanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip
          powershell -Command "Expand-Archive -Path sonar-scanner-cli.zip -DestinationPath ."
          setx PATH "%PATH%;%CD%\\sonar-scanner-4.7.0.2747-windows\\bin
      
      # - name: Verify SonarScanner Installation
      #   run: |
      #     dir sonar-scanner-4.7.0.2747-windows\bin
      #     echo %PATH%

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN:  sqp_6d305ee1584616ec1a13f63369d0f5315163a4b4
        run: |
          C:\sonar-scanner-cli-6.1.0.4477-windows-x64\sonar-scanner-6.1.0.4477-windows-x64\bin\sonar-scanner.bat -D"sonar.projectKey=sonnerqube-testing" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.token=sqp_6d305ee1584616ec1a13f63369d0f5315163a4b4"
