name: CI/CD workflow for Maven Build and Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=SonarQube-Testing
      env:
        SONAR_TOKEN: sqa_09bbf7863f5d1acd50f47c15829404973b7e6c27
        SONAR_HOST_URL: http://localhost:9000
